permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
gems: [jekyll-paginate]
# 作者信息
author: 
  name: 伍小二
  email: wuxiaoer@gmail.com 
  link: http://xiaoerwu.github.io
  weibo: http://weibo.com/u/1644738262
  github: http://github.com/xiaoerwu
  music: http://site.douban.com/wuxiaoer
  linkedin: https://www.linkedin.com/pub/wuxiaoer

# 站点信息
title: 伍小二的博客
description: My personal blog
url: http://xiaoerwu.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/wing.png
favicon: /public/img/wing.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: wuxiaoer 

# 主题设置，自动激活某个标签
active: Tech 

# 首页除了最新文章外显示分类
cates: 
  - python 
  - Research

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  resume: 简历
